defaults:
  - _self_
  - env: env_im
  - learning: im_mlp
  - run: train_run_legs

notes: "Default Notes"
project: kinesis_legs
datadir: legs
exp_name: &exp_name kinesis_im
headless: True
seed: 0
no_log: False
resume_str: null
num_threads: 1
test: False 
output_dir: data/trained_models/legs/${exp_name}
epoch: 0
im_eval: False
num_primitive: 3
num_experts: 3

hydra:
  job:
    name: ${exp_name}
    env_set:
      OMP_NUM_THREADS: 1
  run:
    dir: data/trained_models/legs/${exp_name}

